PagedGeometry: Forests::BatchedGeometry Class Reference
Forests::BatchedGeometry Class Reference
A "lightweight" version of Ogre::StaticGeometry, which gives you a little more control over the batch materials, etc.
#include <BatchedGeometry.h>
Classes
class SubBatch
Visible chunk of geometry.
Public Types
typedef std::map< Ogre::String, SubBatch * > TSubBatchMap
Stores a list of GeomBatch'es, using a format string (generated with getGeometryFormatString()) as the key value.
typedef Ogre::MapIterator< TSubBatchMap > TSubBatchIterator
typedef Ogre::ConstMapIterator< TSubBatchMap > TConstSubBatchIterator
Public Types inherited from Ogre::MovableObject
typedef vector< ShadowRenderable * >::type ShadowRenderableList
typedef VectorIterator< ShadowRenderableList > ShadowRenderableListIterator
Public Types inherited from Ogre::ShadowCaster
typedef vector< ShadowRenderable * >::type ShadowRenderableList
typedef VectorIterator< ShadowRenderableList > ShadowRenderableListIterator
Public Member Functions
BatchedGeometry (Ogre::SceneManager *mgr, Ogre::SceneNode *rootSceneNode)
Constructor.
TConstSubBatchIterator getSubBatchIterator () const
TSubBatchIterator getSubBatchIterator ()
virtual void addEntity (Ogre::Entity *ent, const Ogre::Vector3 &position, const Ogre::Quaternion &orientation=Ogre::Quaternion::IDENTITY, const Ogre::Vector3 &scale=Ogre::Vector3::UNIT_SCALE, const Ogre::ColourValue &color=Ogre::ColourValue::White)
void build ()
void clear ()
Ogre::Vector3 _convertToLocal (const Ogre::Vector3 &globalVec) const
const Ogre::AxisAlignedBox & getBoundingBox (void) const
Ogre::Real getBoundingRadius (void) const
Public Member Functions inherited from Ogre::MovableObject
MovableObject (const String &name)
MovableObjectFactory * _getCreator (void) const
LightList * _getLightList ()
SceneManager * _getManager (void) const
virtual const Matrix4 & _getParentNodeFullTransform (void) const
virtual void _notifyAttached (Node *parent, bool isTagPoint=false)
virtual void _notifyCreator (MovableObjectFactory *fact)
virtual void _notifyManager (SceneManager *man)
virtual void _notifyMoved (void)
virtual void _releaseManualHardwareResources ()
virtual void _restoreManualHardwareResources ()
void addQueryFlags (uint32 flags)
void addVisibilityFlags (uint32 flags)
virtual AnimableValuePtr createAnimableValue (const String &valueName)
void detachFromParent (void)
const StringVector & getAnimableValueNames (void) const
bool getCastShadows (void) const
const AxisAlignedBox & getDarkCapBounds (const Light &light, Real dirLightExtrusionDist) const
EdgeData * getEdgeList (void)
const AxisAlignedBox & getLightCapBounds (void) const
uint32 getLightMask () const
Listener * getListener (void) const
const String & getName (void) const
Node * getParentNode (void) const
SceneNode * getParentSceneNode (void) const
Real getPointExtrusionDistance (const Light *l) const
uint32 getQueryFlags (void) const
bool getReceivesShadows ()
Real getRenderingDistance (void) const
Real getRenderingMinPixelSize () const
uint8 getRenderQueueGroup (void) const
ShadowRenderableListIterator getShadowVolumeRenderableIterator (ShadowTechnique shadowTechnique, const Light *light, HardwareIndexBufferSharedPtr *indexBuffer, size_t *indexBufferUsedSize, bool extrudeVertices, Real extrusionDist, unsigned long flags=0)
virtual uint32 getTypeFlags (void) const
const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
const UserObjectBindings & getUserObjectBindings () const
uint32 getVisibilityFlags (void) const
bool getVisible (void) const
virtual const AxisAlignedBox & getWorldBoundingBox (bool derive=false) const
virtual const Sphere & getWorldBoundingSphere (bool derive=false) const
bool hasEdgeList (void)
bool isAttached (void) const
bool isDebugDisplayEnabled (void) const
virtual bool isInScene (void) const
bool isParentTagPoint () const
const LightList & queryLights (void) const
void removeQueryFlags (uint32 flags)
void removeVisibilityFlags (uint32 flags)
void setCastShadows (bool enabled)
void setDebugDisplayEnabled (bool enabled)
void setLightMask (uint32 lightMask)
void setListener (Listener *listener)
void setQueryFlags (uint32 flags)
void setRenderingDistance (Real dist)
void setRenderingMinPixelSize (Real pixelSize)
virtual void setRenderQueueGroup (uint8 queueID)
virtual void setRenderQueueGroupAndPriority (uint8 queueID, ushort priority)
void setUserAny (const Any &anything)
void setVisibilityFlags (uint32 flags)
void setVisible (bool visible)
Public Member Functions inherited from Ogre::AnimableObject
const StringVector & getAnimableValueNames (void) const
Static Protected Member Functions
static Ogre::String getFormatString (Ogre::SubEntity *ent)
static void extractVertexDataFromShared (const Ogre::MeshPtr &mesh)
Protected Attributes
bool m_Built
bool m_BoundsUndefined
Ogre::Vector3 m_vecCenter
Ogre::AxisAlignedBox m_boundsAAB
TSubBatchMap m_mapSubBatch
Static Protected Attributes
static const size_t s_vertexType2Size [Ogre::VET_COLOUR_ABGR+1]
Internal matrix for remap vertex type to vertex size instead call VertexElement::getTypeSize.
Additional Inherited Members
Static Public Member Functions inherited from Ogre::MovableObject
static void clearShadowRenderableList (ShadowRenderableList &shadowRenderables)
static void extrudeVertices (const HardwareVertexBufferSharedPtr &vertexBuffer, size_t originalVertexCount, const Vector4 &lightPos, Real extrudeDist)
static uint32 getDefaultQueryFlags ()
static uint32 getDefaultVisibilityFlags ()
static void setDefaultQueryFlags (uint32 flags)
static void setDefaultVisibilityFlags (uint32 flags)
Static Public Member Functions inherited from Ogre::ShadowCaster
static void clearShadowRenderableList (ShadowRenderableList &shadowRenderables)
static void extrudeVertices (const HardwareVertexBufferSharedPtr &vertexBuffer, size_t originalVertexCount, const Vector4 &lightPos, Real extrudeDist)
Detailed Description
A "lightweight" version of Ogre::StaticGeometry, which gives you a little more control over the batch materials, etc.
Member Function Documentation
void BatchedGeometry::build (void)
Make sure the batch hasn't already been built
References Ogre::SceneNode::attachObject(), Ogre::SceneNode::createChildSceneNode(), Ogre::SceneManager::destroySceneNode(), Ogre::AxisAlignedBox::getCenter(), Ogre::Camera::getDerivedPosition(), Ogre::AxisAlignedBox::getMaximum(), Ogre::AxisAlignedBox::getMinimum(), Ogre::SceneNode::getOrientation(), Ogre::SceneNode::getParent(), Ogre::SceneNode::getParentSceneNode(), Ogre::RenderQueue::getQueueGroup(), Ogre::MovableObject::getRenderingDistance(), Ogre::MovableObject::getRenderQueueGroup(), Ogre::Quaternion::Inverse(), Ogre::Vector3::length(), OGRE_EXCEPT, Ogre::SceneNode::removeAllChildren(), Ogre::SceneNode::removeAndDestroyChild(), Ogre::AxisAlignedBox::setMaximum(), Ogre::AxisAlignedBox::setMinimum(), and Ogre::Vector3::squaredLength().
Referenced by Forests::BatchPage::build().
Member Data Documentation
const size_t BatchedGeometry::s_vertexType2Size static protected
Initial value:
= {
   VertexElement::getTypeSize(VET_FLOAT1),
   VertexElement::getTypeSize(VET_FLOAT2),
   VertexElement::getTypeSize(VET_FLOAT3),
   VertexElement::getTypeSize(VET_FLOAT4),
   VertexElement::getTypeSize(VET_COLOUR),
   VertexElement::getTypeSize(VET_SHORT1),
   VertexElement::getTypeSize(VET_SHORT2),
   VertexElement::getTypeSize(VET_SHORT3),
   VertexElement::getTypeSize(VET_SHORT4),
   VertexElement::getTypeSize(VET_UBYTE4),
   VertexElement::getTypeSize(VET_COLOUR_ARGB),
   VertexElement::getTypeSize(VET_COLOUR_ABGR)
}
Internal matrix for remap vertex type to vertex size instead call VertexElement::getTypeSize.
For Ogre 1.7.2 and 1.7.3 VertexElementType enum writed as.
VET_FLOAT1 = 0 VET_FLOAT2 = 1 VET_FLOAT3 = 2 VET_FLOAT4 = 3 VET_COLOUR = 4 VET_SHORT1 = 5 VET_SHORT2 = 6 VET_SHORT3 = 7 VET_SHORT4 = 8 VET_UBYTE4 = 9 VET_COLOUR_ARGB = 10 VET_COLOUR_ABGR = 11
Referenced by Forests::WindBatchedGeometry::WindSubBatch::build(), and Forests::BatchedGeometry::SubBatch::build().