PagedGeometry: Forests::ImpostorTextureResourceLoader Class Reference
Forests::ImpostorTextureResourceLoader Class Reference
Responsible for making sure that the texture is rerendered when the texture resource needs to be reloaded.
#include <ImpostorPage.h>
Public Member Functions
ImpostorTextureResourceLoader (ImpostorTexture &impostorTexture)
Ctor.
virtual void loadResource (Ogre::Resource *resource)
At load time the texture will be rerendered.
Public Member Functions inherited from Ogre::ManualResourceLoader
virtual void prepareResource (Resource *resource)
Protected Attributes
ImpostorTexture & texture
Detailed Description
Responsible for making sure that the texture is rerendered when the texture resource needs to be reloaded.
Constructor & Destructor Documentation
ImpostorTextureResourceLoader::ImpostorTextureResourceLoader (ImpostorTexture & impostorTexture)
Ctor.
Parameters
renderContext The ImpostorTexture to which this instance belongs.
Referenced by loadResource().
Member Function Documentation
void ImpostorTextureResourceLoader::loadResource (Ogre::Resource * resource) virtual
At load time the texture will be rerendered.
Parameters
resource
Implements Ogre::ManualResourceLoader.
References Ogre::SceneNode::attachObject(), Ogre::ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME, Ogre::Entity::clone(), CMPF_GREATER_EQUAL, Ogre::SceneNode::createChildSceneNode(), Ogre::Pass::createTextureUnitState(), Ogre::SceneManager::destroyCamera(), Ogre::SceneNode::detachAllObjects(), Ogre::SceneNode::detachObject(), FO_LINEAR, FO_NONE, FO_POINT, FOG_NONE, FT_MAG, FT_MIN, FT_MIP, Ogre::Entity::getBoundingBox(), Ogre::Texture::getBuffer(), Ogre::MaterialManager::getDefaultTextureFiltering(), Ogre::Resource::getLoadingState(), getName(), Ogre::Texture::getName(), Ogre::Entity::getName(), Ogre::Entity::getParentSceneNode(), Ogre::Technique::getPass(), Ogre::Entity::getRenderingDistance(), Forests::PagedGeometry::getRenderQueue(), Ogre::Entity::getRenderQueueGroup(), Ogre::Camera::getSceneManager(), Forests::PagedGeometry::getSceneManager(), Ogre::Material::getTechnique(), Ogre::Pass::getTextureUnitState(), Ogre::Entity::getVisible(), ImpostorTextureResourceLoader(), SharedPtr< Texture >::isNull(), Ogre::Resource::LOADSTATE_UNLOADED, MIP_UNLIMITED, PF_A8R8G8B8, Ogre::SceneNode::removeAndDestroyAllChildren(), SBF_ONE_MINUS_SOURCE_ALPHA, SBF_SOURCE_ALPHA, Ogre::SceneManager::SCRQM_INCLUDE, Ogre::Pass::setAlphaRejectSettings(), Ogre::Camera::setAspectRatio(), Ogre::Viewport::setBackgroundColour(), Ogre::Viewport::setClearEveryFrame(), Ogre::MaterialManager::setDefaultTextureFiltering(), Ogre::Pass::setDepthWriteEnabled(), Ogre::Viewport::setDimensions(), Ogre::Camera::setFarClipDistance(), Ogre::Camera::setFOVy(), Ogre::Pass::setLightingEnabled(), Ogre::Camera::setLodBias(), Ogre::Camera::setNearClipDistance(), SharedPtr< Texture >::setNull(), Ogre::Texture::setNumMipmaps(), Ogre::SceneNode::setOrientation(), Ogre::Viewport::setOverlaysEnabled(), Ogre::SceneNode::setPosition(), Ogre::Entity::setRenderingDistance(), Ogre::Entity::setRenderQueueGroup(), Ogre::Pass::setSceneBlending(), Ogre::Viewport::setShadowsEnabled(), Ogre::TextureUnitState::setTextureName(), Ogre::TextureUnitState::setTextureUScroll(), Ogre::TextureUnitState::setTextureVScroll(), Ogre::Entity::setVisible(), TEX_TYPE_2D, Ogre::SceneNode::translate(), and TU_RENDERTARGET.